=== rishabh110493/scicoslab/man/man.dtd
<!ELEMENT MAN (META?,LANGUAGE,TITLE,TYPE,DATE,NAME?,KEYWORD?,SHORT_DESCRIPTION*,
               CALLING_SEQUENCE?,PARAM*,DESCRIPTION?,ITEMIZE*,EXAMPLE?,SEE_ALSO?,
               (AUTHOR|AUTHORS)?,BIBLIO?,USED_FUNCTIONS?)>
<!ELEMENT META (#PCDATA)  	 >

<!ATTLIST META 
PATH 	CDATA 	"SCI/" 
CATEGORY 	CDATA 	"ScilabFunction" 	 
VERSION_SCI 	CDATA 	"2.6" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Matthieu PHILIPPE" 	 
 >
<!ELEMENT LANGUAGE (#PCDATA)  	 >

<!ELEMENT TITLE (#PCDATA)  	 >

<!ELEMENT DATE (#PCDATA)  	 >

<!ELEMENT TYPE (#PCDATA)  	 >

<!ELEMENT NAME (#PCDATA)  	 >

<!ELEMENT KEYWORD (#PCDATA)  	 >

<!ELEMENT SHORT_DESCRIPTION (#PCDATA | P|PP)*  	 >

<!ATTLIST SHORT_DESCRIPTION name CDATA #REQUIRED       >

<!ELEMENT USED_FUNCTIONS (#PCDATA |P|PP|VERB|EM|BD|TT)*  	 >

<!ELEMENT CALLING_SEQUENCE (#PCDATA|PP|CALLING_SEQUENCE_ITEM)*  	 >

<!ELEMENT PARAM (#PCDATA|PARAM_ITEM|PARAM_INDENT|ITEMIZE|P|TABLE|PP)*  	 >

<!ATTLIST PARAM target (out|in) #IMPLIED  	 >

<!ELEMENT PARAM_ITEM ((PARAM_NAME,PARAM_DESCRIPTION,PARAM_ITEM*)|PARAM_INDENT*)  	 >

<!ELEMENT PARAM_NAME (#PCDATA|VERB)*  	 >

<!ELEMENT PARAM_DESCRIPTION (#PCDATA|P|PP|TABLE|PARAM_INDENT|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ELEMENT PARAM_INDENT (#PCDATA|PARAM_ITEM|PARAM_INDENT|P|PP|TABLE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT DESCRIPTION (#PCDATA|P|PP|TABLE|DESCRIPTION_ITEM|DESCRIPTION_INDENT|ITEMIZE|VERB|EM|BD|TT|VERBATIM|LINK)*  	 >

<!ELEMENT DESCRIPTION_ITEM (#PCDATA|P|PP|TABLE|ITEMIZE|VERB|EM|BD|TT|VERBATIM|DESCRIPTION_INDENT|DESCRIPTION_ITEM|LINK)*  	 >

<!ATTLIST DESCRIPTION_ITEM label CDATA #IMPLIED  	 >

<!ELEMENT DESCRIPTION_INDENT (#PCDATA|DESCRIPTION_ITEM|DESCRIPTION_INDENT|P|PP|TABLE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT EXAMPLE (#PCDATA)  	 >

<!ELEMENT SEE_ALSO (SEE_ALSO_ITEM)+  	 >


<!ELEMENT AUTHORS (#PCDATA|P|PP|AUTHORS_ITEM|ITEMIZE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT AUTHORS_ITEM (#PCDATA|P|PP|ITEMIZE|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ATTLIST AUTHORS_ITEM label CDATA #IMPLIED  	 >





<!ELEMENT AUTHOR (#PCDATA)  	 >

<!ELEMENT BIBLIO (#PCDATA|P|PP)*  	 >

<!ELEMENT CALLING_SEQUENCE_ITEM (#PCDATA)  	 >

<!ELEMENT SEE_ALSO_ITEM (#PCDATA|P|A|LINK)*  	 >

<!ELEMENT A (#PCDATA)*  	 >

<!ATTLIST A href CDATA #REQUIRED  	 >

<!ELEMENT LINK (#PCDATA)*      >

<!ELEMENT P (#PCDATA|TABLE|ITEM|EMPTY|VERB|EM|BD|TT|A|LINK)*  	 >

<!ELEMENT VERBATIM (#PCDATA)  	 >

<!ELEMENT ITEM (#PCDATA|TABLE|ITEM|ITEMIZE|P|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ATTLIST ITEM label CDATA #IMPLIED  	 >

<!ELEMENT ITEMIZE (TABLE|ITEM|ITEMIZE|P|VERBATIM)*  	 >

<!ATTLIST ITEMIZE label CDATA #IMPLIED  	 >

<!ELEMENT TABLE (TABLE_NEW_ROW)+  	 >

<!ELEMENT TABLE_NEW_ROW (TABLE_NEW_COLUMN)+  	 >

<!ELEMENT TABLE_NEW_COLUMN (#PCDATA|VERB|EM|BD|TT)* 	 >

<!ELEMENT MATH (#PCDATA ) 	 >

<!ELEMENT VERB (#PCDATA )>

<!ELEMENT EM (#PCDATA )>

<!ELEMENT BD (#PCDATA )>

<!ELEMENT TT (#PCDATA )>

<!ELEMENT REMARKS (#PCDATA )>

=== rishabh110493/scicoslab/contrib/cs5/man/lpf.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>lpf  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="lpf ">  Travel time functions  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[ta,dta,cta]=lpf(F,lpp,nf)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>F  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of flows in each arc
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>lpp  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : parameters of the travel time functions (ttf) for each arc
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nf  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : model for the ttf
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : travel time of each arc for the given flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>dta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : derivate of the ttf for the given arc flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>cta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : integral of the ttf for the given arc flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Computes the travel time of each arc for the given flow using the travel time
    functions with parameters lpp and formula nf. Each colum of lpp is of the form
    [t0;ca;ma;ba] where the coefficients t0 and ca have the meanings:
  </P>
 

  <DESCRIPTION_ITEM  label='t0'> 
    : free-flow travel time
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='ca'> 
    : practical capacity of the link 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='The different formulae for the ttf are:'> 
    
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=0 -&gt; c=t0+ma/ca*F+ma*(max(0,F-ca))^ba, with ba&gt;=1'> 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=1 -&gt; c=t0*exp((F/ca)-1), with ca&gt;0'> 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=2 -&gt; c=t0*2^((F/ca)-1), with ca&gt;0'> 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=3 -&gt; c=t0*(1+0.15*(F/ca)^ma), with ma&gt;=1 and ca&gt;0'> 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=4 -&gt; c=t0+log(ca)-log(ca-F), with ca&gt;0'> 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=5 -&gt; c=ba-ca*(t0-ba)/(F-ca), with ca&gt;0'> 
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label='nf=6 -&gt; c=t0+ca*F+ma*F^ba, with ba&gt;1'> 
    
  </DESCRIPTION_ITEM>
 
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample('Small');
[g,d,lpp,nf]=Net2Par(net);
F=rand(1,9);
[ta,dta,cta]=lpf(F,lpp,nf) 
// shows the function with the different parameters
dlpf(0.1,.01,5,lpp,6);
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficExample</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>dlpf</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/TrafficExample.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>TrafficExample  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="TrafficExample">  Traffic network example  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>net=TrafficExample(&quot;name&quot;,p1,p2,p3,p4)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : NetList of the traffic network
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>name  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string to choose among &quot;Braess&quot;, &quot;Diamond&quot;, &quot;Empty&quot;, &quot;Nguyen Dupuis&quot;, &quot;Normal Random City&quot;, &quot;Random City&quot;, &quot;Regular City&quot;,  &quot;Sioux Falls&quot;, &quot;Small&quot;, &quot;Steenbrink&quot;, &quot;Triangle&quot;.
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>p1, p2,  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>p3, p4  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals needed for examples: Regular City, Random City and Normal Random City 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
     Generates a net-list choosing among many traffic network
    examples:
  </P>
  <P>
    -&quot;Braess&quot; -&gt; 4 nodes, 5 links and 1 demand. Linear travel time
    functions.
  </P>
  <P>
    -&quot;Chicago&quot; -&gt; 546 nodes, 2176 links and 93135 demands. Real large example.
  </P>
  <P>
    -&quot;Diamond&quot; -&gt; 8 nodes, 14 links and 1 demand, diamond shaped network.
  </P>
  <P>
    -&quot;Empty&quot; -&gt;  2 nodes and 1 link graph.
  </P>
  <P>
    -&quot;Nguyen Dupuis&quot; -&gt; 13 nodes, 19 links and 4 demands network. Linear travel
    time functions.
  </P>
  <P>
    -&quot;Normal Random City&quot; -&gt; A net is generated using RandomNNet(p1,p2,p3,p4).
  </P>
  <P>
    -&quot;Random City&quot; -&gt; A net is generated using RandomNet(p1,p2,p3,p4).
  </P>
  <P>
    -&quot;Regular City&quot; -&gt;  A net is generated using Regular(p1,p2,p3).
  </P>
  <P>
    -&quot;Sioux Falls&quot; -&gt; 24 nodes, 76 links and 528 demands network. Travel time
    functions of power 4.
  </P>
  <P>
    -&quot;Small&quot; -&gt; 4 nodes, 9 links and 2 demands network. Quadratic travel time
    functions.
  </P>
  <P>
    -&quot;Steenbrink&quot; -&gt; 9 nodes, 36 links and 12 demands network. Linear travel time
    functions.
  </P>
  <P>
    -&quot;Triangle&quot; -&gt;  3 nodes and 6 links network
  </P>
  <P>
  </P>
  <P>
    These examples can be used as starting point to make different networks.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample("Sioux Falls");
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>RandomNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>RandomNNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>Regular</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/LogitNELS.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>LogitNELS  </TITLE>
  <TYPE>CiudadSim Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="LogitNELS "> Net Logit Equilibrium (Linear Search)  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>bench=LogitNELS(theta,method,eps,Niter)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>theta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : stochasticity parameter 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>method  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : macro among LogitB, LogitD, LogitMB, LogitMD
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>eps  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : convergence error test 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>Niter  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximal number of iteration 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>bench  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : niter x 5  matrix
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : global variable NetList 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Compute the logit traffic equilibrium using a
    logit method among LogitB, LogitD, LogitMB, LogitMD
    the travel time is taken in %net.links.time
    and the assigned fow is put in the field
    %net.links.flow of the variable %net which
    is a NetList which must be declared global.
  </P>
  <P>
    The equilibrium is computed using a linear search based
    on the corresponding deterministic criterium as approximated
    Lyapounov function. This method is valid at least for
    large theta.
  </P>
  <P>
    If %net.gp.verbose=%T  convergence informations are displayed.
    These informations are returned by the function in the variable %net.gp.bench.
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
// Graph generation (the graph must be stongly connected)
%net=TrafficExample("Steenbrink");
//theta definition (almost deterministic)
theta=10
// Flow calculation
LogitNELS(theta,LogitMD,1.e-6,40);
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>LogitD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitB</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitMB</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitMD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitN</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitNE</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/IntroTrfAsg.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>IntroTrfAsg  </TITLE>
  <TYPE> Traffic-Toolbox Comments  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="IntroTrfAsg"> Introduction to the Traffic Assignment Toolbox  </SHORT_DESCRIPTION>
  <DESCRIPTION>
  <P>
     The purpose of the toolbox is to solve traffic assignment problems. A good reference is Michael Patriksson&apos;s book &quot;The Traffic Assignment Problem, Models and
    Methods&quot;.
  </P>
  <P>
  </P>
  <P>
    To define the problem we need :
  </P>
  <P>
  </P>
 

  <DESCRIPTION_ITEM  label=''> 
    1) The Traffic Network : an oriented graph G where nn nodes represent places or cities, and na arcs represent  links or roads.
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label=''> 
    2) The Link Performance Functions (also known as travel time functions): the travel time as a function of the flow in the arc. Seven formulae are used needing 4 parameters. Once a formula is chosen for the whole network, the parameters are defined in a 4 x na matrix.
  </DESCRIPTION_ITEM>

  <DESCRIPTION_ITEM  label=''> 
    3) The Origin-Destination traffic demand pairs (OD-pairs also called commodities) : are given by an initial node, a final node and a flow. The nd OD-pairs are defined by a 3 x nd matrix.
  </DESCRIPTION_ITEM>
 
  </DESCRIPTION>
  <ITEMIZE label=''>
  <P>
     All the data is stored in a scilab structure called a &quot;NetList&quot; that plays the role of a geographic data basis which can be visualized by &quot;ShowNet&quot; and edited inside &quot;metanet&quot; or &quot;scigraph&quot;. This NetList is build by &quot;MakeNet&quot;.
  </P>
  <P>
     
  </P>
  <P>
    The traffic assignment is computed by &quot;TrafficAssig&quot;. The results are stored in the Geographic Data Basis and can be visualized with &quot;ShowNet&quot;. 
  </P>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>MakeNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/AddDemands.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>AddDemands  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="AddDemands ">  Add demands to a net list  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>AddDemands(td,hd,demand)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : global variable Netlist databasis
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>td  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, tail nodes numbers of the added demands
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>hd  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, head nodes numbers of the added demands
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>demand  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, the values of the added demands
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    AddDemands adds demands to a net list.
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Diamond');
ShowNet()
// Add a new demand from node 3 to node 2 with value 10 in the same net
AddDemands(3,2,10);
// We can see the modifications with
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>AddLinks</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>AddNodes</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>MakeNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/Probit.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>Probit  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="Probit ">  Probit-based stochastic network assignment  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[f,s]=Probit(net,ta,beta,accuracy,kmax)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <P>  </P>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : link travel time
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>beta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : variance of the perceived travel time over a road segment of unit travel time
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>accuracy  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : precision
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>kmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximum number of iterations
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow (disaggregated by commodity)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>s  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : standard deviation for the assigned flow f 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Assigns the flow with a Probit-based model. In this model
    the perceived travel time along any given path is normally 
    distributed with mean ta and variance beta*ta.
    The algorithm use to make the assignment is base on a
    Monte Carlo simulation of the perceived link travel times.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample("Small");
ta=net.links.lpf_data(1,:);
// uses the example net Small
[f,s]=Probit(net,ta,0.1,0.001,7);

   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IAON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/AddLinks.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>AddLinks  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="AddLinks ">  Add links to a net list  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>AddLinks(tl,hl,lpp)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : the global Netlist variable databasis
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>tl  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, tail nodes numbers of the added links
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>hl  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, head nodes numbers of the added links
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>lpp  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : 4 x nl matrix, travel time function parameters, where nl is the  number of added links 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    AddLinks adds links to a net list.
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Diamond');
ShowNet()
// Add a new link from node 3 to node 4 with lpp=[0;0;1;1]
AddLinks(3,4,[0;0;1;1]);
// We can see the modifications with
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>AddNodes</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>AddDemands</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>MakeNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/fw.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>FW  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="FW ">  Frank-Wolfe traffic assignment algorithm  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[F,ta,ben]=FW(net,kmax,tol)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <P>  </P>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>kmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximum number of iterations
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>tol  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : precision
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>F  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : link travel time for the assigned flow F
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ben  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : ni x 5 matrix (ni number of performed general iterations) benchmark information  
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Assigns the flow with the Frank-Wolfe algorithm.
    After an initial AON assignment the link costs are updated
    and a new assignment is computed. The new assignment is combined
    with the previous one in a way that minimizes the global cost.
    The algorithm terminates when the number of iterations kmax is reached
    or the change in link costs is less than tol.
    When they are not given tol and kmax have the default values 1e-6 and
    20.
  </P>
  <P>
    The matrix ben contains intermediary informations on the
    algorithm. For each iteration it gives the iteration number, time
    spent, cost, memory used and an convergence error evaluation.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample("Small");
/// generates a network with 4 nodes, 9 arcs and 2 OD-pairs
[F,ta,ben]=FW(net);
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IAON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>DSD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>
