=== rishabh110493/scicoslab/man/man.dtd
<!ELEMENT MAN (META?,LANGUAGE,TITLE,TYPE,DATE,NAME?,KEYWORD?,SHORT_DESCRIPTION*,
               CALLING_SEQUENCE?,PARAM*,DESCRIPTION?,ITEMIZE*,EXAMPLE?,SEE_ALSO?,
               (AUTHOR|AUTHORS)?,BIBLIO?,USED_FUNCTIONS?)>
<!ELEMENT META (#PCDATA)  	 >

<!ATTLIST META 
PATH 	CDATA 	"SCI/" 
CATEGORY 	CDATA 	"ScilabFunction" 	 
VERSION_SCI 	CDATA 	"2.6" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Matthieu PHILIPPE" 	 
 >
<!ELEMENT LANGUAGE (#PCDATA)  	 >

<!ELEMENT TITLE (#PCDATA)  	 >

<!ELEMENT DATE (#PCDATA)  	 >

<!ELEMENT TYPE (#PCDATA)  	 >

<!ELEMENT NAME (#PCDATA)  	 >

<!ELEMENT KEYWORD (#PCDATA)  	 >

<!ELEMENT SHORT_DESCRIPTION (#PCDATA | P|PP)*  	 >

<!ATTLIST SHORT_DESCRIPTION name CDATA #REQUIRED       >

<!ELEMENT USED_FUNCTIONS (#PCDATA |P|PP|VERB|EM|BD|TT)*  	 >

<!ELEMENT CALLING_SEQUENCE (#PCDATA|PP|CALLING_SEQUENCE_ITEM)*  	 >

<!ELEMENT PARAM (#PCDATA|PARAM_ITEM|PARAM_INDENT|ITEMIZE|P|TABLE|PP)*  	 >

<!ATTLIST PARAM target (out|in) #IMPLIED  	 >

<!ELEMENT PARAM_ITEM ((PARAM_NAME,PARAM_DESCRIPTION,PARAM_ITEM*)|PARAM_INDENT*)  	 >

<!ELEMENT PARAM_NAME (#PCDATA|VERB)*  	 >

<!ELEMENT PARAM_DESCRIPTION (#PCDATA|P|PP|TABLE|PARAM_INDENT|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ELEMENT PARAM_INDENT (#PCDATA|PARAM_ITEM|PARAM_INDENT|P|PP|TABLE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT DESCRIPTION (#PCDATA|P|PP|TABLE|DESCRIPTION_ITEM|DESCRIPTION_INDENT|ITEMIZE|VERB|EM|BD|TT|VERBATIM|LINK)*  	 >

<!ELEMENT DESCRIPTION_ITEM (#PCDATA|P|PP|TABLE|ITEMIZE|VERB|EM|BD|TT|VERBATIM|DESCRIPTION_INDENT|DESCRIPTION_ITEM|LINK)*  	 >

<!ATTLIST DESCRIPTION_ITEM label CDATA #IMPLIED  	 >

<!ELEMENT DESCRIPTION_INDENT (#PCDATA|DESCRIPTION_ITEM|DESCRIPTION_INDENT|P|PP|TABLE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT EXAMPLE (#PCDATA)  	 >

<!ELEMENT SEE_ALSO (SEE_ALSO_ITEM)+  	 >


<!ELEMENT AUTHORS (#PCDATA|P|PP|AUTHORS_ITEM|ITEMIZE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT AUTHORS_ITEM (#PCDATA|P|PP|ITEMIZE|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ATTLIST AUTHORS_ITEM label CDATA #IMPLIED  	 >





<!ELEMENT AUTHOR (#PCDATA)  	 >

<!ELEMENT BIBLIO (#PCDATA|P|PP)*  	 >

<!ELEMENT CALLING_SEQUENCE_ITEM (#PCDATA)  	 >

<!ELEMENT SEE_ALSO_ITEM (#PCDATA|P|A|LINK)*  	 >

<!ELEMENT A (#PCDATA)*  	 >

<!ATTLIST A href CDATA #REQUIRED  	 >

<!ELEMENT LINK (#PCDATA)*      >

<!ELEMENT P (#PCDATA|TABLE|ITEM|EMPTY|VERB|EM|BD|TT|A|LINK)*  	 >

<!ELEMENT VERBATIM (#PCDATA)  	 >

<!ELEMENT ITEM (#PCDATA|TABLE|ITEM|ITEMIZE|P|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ATTLIST ITEM label CDATA #IMPLIED  	 >

<!ELEMENT ITEMIZE (TABLE|ITEM|ITEMIZE|P|VERBATIM)*  	 >

<!ATTLIST ITEMIZE label CDATA #IMPLIED  	 >

<!ELEMENT TABLE (TABLE_NEW_ROW)+  	 >

<!ELEMENT TABLE_NEW_ROW (TABLE_NEW_COLUMN)+  	 >

<!ELEMENT TABLE_NEW_COLUMN (#PCDATA|VERB|EM|BD|TT)* 	 >

<!ELEMENT MATH (#PCDATA ) 	 >

<!ELEMENT VERB (#PCDATA )>

<!ELEMENT EM (#PCDATA )>

<!ELEMENT BD (#PCDATA )>

<!ELEMENT TT (#PCDATA )>

<!ELEMENT REMARKS (#PCDATA )>

=== rishabh110493/scicoslab/contrib/cs5/man/ShowNet.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>ShowNet  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="ShowNet ">  Show a net using Metanet or Scigraph  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>ShowNet()  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>ShowNet(nodes,arcs,fmin,fmax,tmin,tamx,demands,dmin,dmax)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>ShowNet(nodes,arcs,fmin,fmax,tmin,tamx,demands,dmin,dmax,d)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <P>  </P>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : the global NetList varaible databasis
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nodes  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (nodes)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>arcs  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (arcs)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>fmin,fmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals, minimum and maximum flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>tmin,tmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals, minimum and maximum time
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>demands  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (demands)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>dmin,dmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals, minimum and maximum demand 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>d  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : integer, a demand number 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
     ShowNet shows the state of the NetList with the flow and the travel time if they are
    already assigned. The conventions are that the non used arcs are light
    blue, the used arcs are black with their width proportional to the flow. The
    demands are magenta with their width proportional to the demand flow.
    The orientation of the demand arcs is from origin to destination. 
  </P>
  <P>
     It is possible to give a list of nodes, arcs and demands to be shown or
    a predefined string 
  </P>
  <P>
    - For the nodes the strings available are : &quot;all&quot;
    representing all the nodes, and &quot;used&quot; representing the nodes used by some
    route. 
  </P>
  <P>
    - For the arcs the options are &quot;all&quot; or &quot;between&quot; in this case 
    the flow limits are the parameters fmin, fmax and the travel time limits are tmin, tmax.
  </P>
  <P>
    - For the demands the options are &quot;all&quot; or &quot;between&quot; in this case the
    demand limits are dmin,dmax. 
  </P>
  <P>
     It is also possible to choose a demand in order to show the disaggregated flow 
    corresponding to a specific commodity. In this case the
    limits on the flow given by fmin and fmax corresponds to the total
    flow but the width and the colors of the arcs correspond to the
    disaggregated flow.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Steenbrink');
%net.gp.algorithm='DSDisaggregated';
TrafficAssig();
ShowNet() // Shows the net
ShowNet('used','between',1000,2000,0,0,3,0,10000,3)
// Shows the net with the flow corresponding to demand 3, 
// the light blue arcs are not used by the commodity 3
// but by other commodities. The width corresponds to
// the flow of the commodity 3. The arcs not shown have
// total flow less than 1000 or greater than 2000.
   ]]></VERBATIM>
  <P>
    
  </P>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>ShowLinks</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowDemands</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficExample</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/RandomNNet.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>RandomNNet  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="RandomNNet ">  Random generation of traffic network data  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>net=RandomNNet(nn,mna,var,nd,nf)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>nn  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : number of nodes
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>mna  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : mean value of the exterior degree of each node (numbers of leaving arcs)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>var  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : variance of the exterior degree of each node
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nd  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : number of OD-pairs (origin-destination)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nf  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : model chosen for the computation of the travel time
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : resulting network 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Generates randomly the data for the Traffic Assignment Problem. For each node an
    exterior degree is chosen randomly with a normal distribution of mean mna
    and variance var, then the successors are chosen without
    repetition. The value of nf indicates the formula chosen for the computation of
    the travel time, by default it is 6. This way of generating randomly the net if very much
    slower than RandomNet.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=RandomNNet(3,3,1,2);
// generates a network with 3 nodes,2 OD-pairs and form
// each node the number of leaving arcs is normally dis-
// tributed with mean 3 and var 1
ShowNet();
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>RandomNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>Regular</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/LogitN.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>LogitN  </TITLE>
  <TYPE>CiudadSim Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="LogitN "> Net Logit Assignment   </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>LogitN(theta,method)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>theta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : stochasticity parameter 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>method  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : macro among LogitB, LogitD, LogitMB, LogitMD
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>%net global variable NetList  </PARAM_NAME>
  <PARAM_DESCRIPTION>
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Compute the logit traffic assignment using a
    method among LogitB, LogitD, LogitMB, LogitMD
    the travel time is taken in %net.links.time
    and the assigned fow is put in the field
    %net.links.flow of the variable %net which
    is a NetList which must be declared global.
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
// Graph generation (the graph must be stongly connected)
%net=TrafficExample("Steenbrink");
//theta definition (almost determinsitic)
theta=10;
// Flow calculation
LogitN(theta,LogitMB)
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>LogitD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitB</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitMB</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitMD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitNE</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/dsd.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>DSD  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="DSD ">  Disaggregated Simplicial Decomposition algorithm  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[F,ta,ben,f]=DSD(net,routemax,nFW,eps,list_eps,list_itemax)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>[F,ta,f]=dsd(net,routemax,nFW,eps,list_eps,list_itemax)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>routemax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximum number of general iterations
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nFW  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : number of Frank-Wolfe iterations
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>eps  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : general precision
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>list_eps  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : array of precisions, Newton method precision, auxiliar precision and linear search precision
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>list_itemax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : array of maximum number of iterations, Newton iterations, auxiliar iteration and linear search iteration
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>F  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : link travel time for the assigned flow f
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ben  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : ni x 5 matrix (ni number of performed general iterations) benchmark information
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow disaggregated by commodity 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
     Assigns the flow with the disaggregated simplicial decomposition  algorithm.
    This algorithm generates at each iteration a new route for each commodity using AON.
    The traffic is assigned minimizing the total cost over the generated routes using
    a Newton method.
    The version DSD shows performance statistics.
    The version dsd is used mostly inside other algorithms and it does not
    displays any information.
  </P>
  <P>
    The matrix ben contains intermediary informations on the
    algorithm. For each iteration it gives the iteration number, time
    spent, cost, memory used and an convergence error evaluation.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample("Steenbrink");
// uses the example net Steenbrink
[F,ta,ben,f]=DSD(net,20,0,1e-4,[1e-6,1e-7,1e-8],[2,50,100]);
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IAON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/ia.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>IA  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="IA ">  Incremental traffic assignment algorithm  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[f,ta]=IA(net,k)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>k  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : number of iterations of the algorithm
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow (disaggregated by commodity)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of reals, current time for the assigned flow f 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Assigns the flow with the Incremental Assignment algorithm.
    Each origin-destination flow is divided into k equal parts.
    Each part is assigned by AON. The link costs are updated
    using the travel time functions of  the assigned flow f.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample('Small');
[f,ta]=IA(net,10);
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IAON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/AddNodes.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>AddNodes  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="AddNodes ">  Add nodes to a net list  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>AddDemands(nx,ny)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : The global Netlist variable databasis
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nx  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, x coordinates of the added nodes
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ny  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, y coordinates of the added nodes
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>net2  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : the resulting net list 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    AddNodes adds nodes to a net list.
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Diamond');
ShowNet()
// Add 2 new nodes with coordinates x=[346,346] and y=[559,-50]
AddNodes([346,346],[559,-50]);
// We can see the modifications with
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>AddDemands</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>AddLinks</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>MakeNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/AONd.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>AONd  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="AONd ">  All or Nothing traffic assignment algorithm   </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[F,f]=AONd(net)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>[F,f]=AONd(net,t0)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>[F,f]=AONd(tl,hl,t0,nn,origins,td,hd,dd)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList, 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>t0  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector, the link travel time (if not given in net)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>tl, hl  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vectors, tail and head nodes numbers of the links 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nn  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : node number
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>origins  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : origins of the OD pairs
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>td, hd, dd  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vectors, tail and head nodes numbers of the demands, and demands values
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>F  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow disaggregated by commodity 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Displays the non feasible OD pairs, if there are some. Those pairs are
    ignored in the assignment. Assigns the flow with the All or Nothing
    algorithm. For each OD-pair it looks for the minimum travel time path
    and assigns all the demand to this path. The travel time of the links are given by t0 or by the corresponding field in net.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Nguyen Dupuis'); 
// we can see the Net 
ShowNet(); 
//we add a non feasible OD pair 
AddDemands(8,1,10); 
ShowNet() 
[F,f]=AONd(%net); 
   ]]></VERBATIM>
  <P>
    
  </P>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IA</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IAON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/ShowLinks.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>ShowLinks  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="ShowLinks ">  Shows the links of a net using Metanet or Scigraph  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>ShowLinks()  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>ShowLinks(nodes,arcs,fmin,fmax,tmin,tamx)  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>ShowLinks(nodes,arcs,fmin,fmax,tmin,tamx,d)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <P>  </P>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : the global NetList variable databasis
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nodes  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (nodes)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>arcs  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (arcs)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>fmin,fmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals, minimum and maximum flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>tmin,tmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals, minimum and maximum time 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>d  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : integer, a specific demand  
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
     Similar to ShowNet but it doesn&apos;t show the demands, it  only shows the
    links of %net  that verify the conditions given by the
    parameters (see ShowNet). If a demand is indicated, then the flow
    shown is the corresponding to that demand.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Steenbrink');
%net.gp.algorithm='AON';
TrafficAssig();
ShowLinks() // Shows the net
ShowLinks('used','between',3000,6000,0,0,3)
// Shows the net with the flow corresponding to demand 3, 
// the light blue arcs are not used by the commodity 3
// but by other commodities. The width corresponds to
// the flow of the commodity 3. The arcs not shown have
// total flow less than 3000 or greater than 6000.
   ]]></VERBATIM>
  <P>
    
  </P>
  </ITEMIZE>
  <SEE_ALSO>
<SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>    
<SEE_ALSO_ITEM> <LINK>TrafficExample</LINK></SEE_ALSO_ITEM>    
<SEE_ALSO_ITEM> <LINK>TrafficExample</LINK></SEE_ALSO_ITEM>
<SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>    
<SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     
<SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>
