=== rishabh110493/scicoslab/man/man.dtd
<!ELEMENT MAN (META?,LANGUAGE,TITLE,TYPE,DATE,NAME?,KEYWORD?,SHORT_DESCRIPTION*,
               CALLING_SEQUENCE?,PARAM*,DESCRIPTION?,ITEMIZE*,EXAMPLE?,SEE_ALSO?,
               (AUTHOR|AUTHORS)?,BIBLIO?,USED_FUNCTIONS?)>
<!ELEMENT META (#PCDATA)  	 >

<!ATTLIST META 
PATH 	CDATA 	"SCI/" 
CATEGORY 	CDATA 	"ScilabFunction" 	 
VERSION_SCI 	CDATA 	"2.6" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Matthieu PHILIPPE" 	 
 >
<!ELEMENT LANGUAGE (#PCDATA)  	 >

<!ELEMENT TITLE (#PCDATA)  	 >

<!ELEMENT DATE (#PCDATA)  	 >

<!ELEMENT TYPE (#PCDATA)  	 >

<!ELEMENT NAME (#PCDATA)  	 >

<!ELEMENT KEYWORD (#PCDATA)  	 >

<!ELEMENT SHORT_DESCRIPTION (#PCDATA | P|PP)*  	 >

<!ATTLIST SHORT_DESCRIPTION name CDATA #REQUIRED       >

<!ELEMENT USED_FUNCTIONS (#PCDATA |P|PP|VERB|EM|BD|TT)*  	 >

<!ELEMENT CALLING_SEQUENCE (#PCDATA|PP|CALLING_SEQUENCE_ITEM)*  	 >

<!ELEMENT PARAM (#PCDATA|PARAM_ITEM|PARAM_INDENT|ITEMIZE|P|TABLE|PP)*  	 >

<!ATTLIST PARAM target (out|in) #IMPLIED  	 >

<!ELEMENT PARAM_ITEM ((PARAM_NAME,PARAM_DESCRIPTION,PARAM_ITEM*)|PARAM_INDENT*)  	 >

<!ELEMENT PARAM_NAME (#PCDATA|VERB)*  	 >

<!ELEMENT PARAM_DESCRIPTION (#PCDATA|P|PP|TABLE|PARAM_INDENT|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ELEMENT PARAM_INDENT (#PCDATA|PARAM_ITEM|PARAM_INDENT|P|PP|TABLE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT DESCRIPTION (#PCDATA|P|PP|TABLE|DESCRIPTION_ITEM|DESCRIPTION_INDENT|ITEMIZE|VERB|EM|BD|TT|VERBATIM|LINK)*  	 >

<!ELEMENT DESCRIPTION_ITEM (#PCDATA|P|PP|TABLE|ITEMIZE|VERB|EM|BD|TT|VERBATIM|DESCRIPTION_INDENT|DESCRIPTION_ITEM|LINK)*  	 >

<!ATTLIST DESCRIPTION_ITEM label CDATA #IMPLIED  	 >

<!ELEMENT DESCRIPTION_INDENT (#PCDATA|DESCRIPTION_ITEM|DESCRIPTION_INDENT|P|PP|TABLE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT EXAMPLE (#PCDATA)  	 >

<!ELEMENT SEE_ALSO (SEE_ALSO_ITEM)+  	 >


<!ELEMENT AUTHORS (#PCDATA|P|PP|AUTHORS_ITEM|ITEMIZE|VERB|EM|BD|TT|VERBATIM)*  	 >

<!ELEMENT AUTHORS_ITEM (#PCDATA|P|PP|ITEMIZE|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ATTLIST AUTHORS_ITEM label CDATA #IMPLIED  	 >





<!ELEMENT AUTHOR (#PCDATA)  	 >

<!ELEMENT BIBLIO (#PCDATA|P|PP)*  	 >

<!ELEMENT CALLING_SEQUENCE_ITEM (#PCDATA)  	 >

<!ELEMENT SEE_ALSO_ITEM (#PCDATA|P|A|LINK)*  	 >

<!ELEMENT A (#PCDATA)*  	 >

<!ATTLIST A href CDATA #REQUIRED  	 >

<!ELEMENT LINK (#PCDATA)*      >

<!ELEMENT P (#PCDATA|TABLE|ITEM|EMPTY|VERB|EM|BD|TT|A|LINK)*  	 >

<!ELEMENT VERBATIM (#PCDATA)  	 >

<!ELEMENT ITEM (#PCDATA|TABLE|ITEM|ITEMIZE|P|VERB|EM|BD|TT|VERBATIM|A|LINK)*  	 >

<!ATTLIST ITEM label CDATA #IMPLIED  	 >

<!ELEMENT ITEMIZE (TABLE|ITEM|ITEMIZE|P|VERBATIM)*  	 >

<!ATTLIST ITEMIZE label CDATA #IMPLIED  	 >

<!ELEMENT TABLE (TABLE_NEW_ROW)+  	 >

<!ELEMENT TABLE_NEW_ROW (TABLE_NEW_COLUMN)+  	 >

<!ELEMENT TABLE_NEW_COLUMN (#PCDATA|VERB|EM|BD|TT)* 	 >

<!ELEMENT MATH (#PCDATA ) 	 >

<!ELEMENT VERB (#PCDATA )>

<!ELEMENT EM (#PCDATA )>

<!ELEMENT BD (#PCDATA )>

<!ELEMENT TT (#PCDATA )>

<!ELEMENT REMARKS (#PCDATA )>

=== rishabh110493/scicoslab/examples/man-examples-xml/helpdir1/example1.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../../man/man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>example1  </TITLE>
  <TYPE>Scilab Function  </TYPE>
  <DATE>April 1993  </DATE>
  <SHORT_DESCRIPTION name="example1"> apropos1  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[X,Y]=fct(a,b,c)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>a  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : what is a
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>b  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : what is b
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>c  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : what is c
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>X  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : what is X
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>Y  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : what is Y
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    This is a blank example to show facilities for adding man pages 
  </P>
  </DESCRIPTION>
  <EXAMPLE><![CDATA[
The example
 ]]></EXAMPLE>
  <AUTHOR>Author   </AUTHOR>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>example2</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/WardropN.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>wardropN  </TITLE>
  <TYPE>Maxplus Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="WardropN "> Wardrop equilibrium ( Newton hybrid method )  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>bench=WardropN(a,k,eps,niter)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>a  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : regularization coefficient (small number)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>k  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reducing regularization coefficient exponential rate (number &gt;= 1)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>eps  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : precision of the convergence test (small number)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>niter  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximal number of iterations
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>bench  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : niter x 5  matrix
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : global variable NetList   
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Compute the Wardrop equilibrium of a transport
    assignment problem by solving the following nodes-links
    variational formulation of the problem:
  </P>
  <P>
    Min_q Sum_l C(f_l)
  </P>
  <P>
    f_l=Sum_i q_li
  </P>
  <P>
    Hq_i=d_i
  </P>
  <P>
    O&lt;=q_li
  </P>
  <P>
    where :
  </P>
  <P>
    - C(f) is a cost in the classes defined by the lpf function,
    - H is is the incidence nodes-arcs matrix of the network,
    - q_li is the flow of the commodity i on the link l,
  </P>
  <P>
    %net is the netlist containing all the information relative to
    the network and the cost function used.
  </P>
  <P>
    The method used is a decomposed newton method
    in the space (q_i,v_i) i=1,p, where the v_i denote the dual
    variables associated to the constraints Hq_i=d_i .
  </P>
  <P>
    The variable a regularizes
    the  matrices giving the potentials.
    At each iteration a is reduced by a factor k.
    We can try first a small a and k=1. 
  </P>
  <P>
    This method is useful mainly in the case of
    a small number of commodities.
  </P>
  <P>
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[

// Definition of the Network
nw=4;
%net=TrafficExample("Regular City",nw,nw);

// Traffic Assignment
bench=WardropN(0.1,2,1.e-4,12);

// Visualization of the NET
ShowNet();

   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>DSD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>Probit</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>MSASUE</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitNE</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitNELS</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/LogitNE.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>LogitNE  </TITLE>
  <TYPE>CiudadSim Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="LogitNE "> Net Logit Equilibrium   </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>bench=LogitNE(theta,method,eps,Niter,Num)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>theta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : stochasticity parameter 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>method  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : macro among LogitB, LogitD, LogitMB, LogitMD
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>eps  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : convergence error test 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>Niter  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximal number of iteration 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>Num  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : number of iteration already done
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>bench  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : niter x 5  matrix
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>%net global variable NetList  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Compute the logit traffic equilibrium using a
    logit method among LogitB, LogitD, LogitMB, LogitMD
    the travel time is taken in %net.links.time
    and the assigned fow is put in the field
    %net.links.flow of the variable %net which
    is a NetList which must be declared global.
  </P>
  <P>
    The equilibrium is computed by a divergent series
    method F[n+1]=F[n]*(1-rho[n])+rho[n]*f
    where f is the new assigned flow computed with the
    travelling time associated to the flow F[n],
    with rho[n]=1/(n+1). 
  </P>
  <P>
    If %net.gp.verbose=%T  convergence informations are displayed.
    These informations are returned by the function in the variable %net.gp.bench.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
// Graph generation (the graph must be stongly connected)
%net=TrafficExample("Steenbrink");
//theta definition (almost determinsitic)
theta=10
// Flow calculation
LogitNE(theta,LogitMD,1.e-6,30,0)
ShowNet()
   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>LogitD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitB</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitMB</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitMD</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitN</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>LogitNELS</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/dlpf.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>dlpf  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="dlpf ">  Plot the travel time functions  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>c=dlpf(f0,inc,f1,lpp,nf)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>f0  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : minimal flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>inc  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : increment
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f1  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximal flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>lpp  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrix of travel time function parameters
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nf  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : ttf formula
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>c  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : matrix of the computed costs 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Plot the travel time functions for the given parameters (lpp) between the minimal flow f0
    and the maximal flow f1 using a step of inc and the formula nf
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample('Small');
[g,d,lpp]=Net2Par(net);
dlpf(0.1,.01,2,lpp,6); // show the function with the different parameters
   ]]></VERBATIM>
  <P>
    
  </P>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficExample</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>lpf</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/ShowDemands.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>ShowDemands  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="ShowDemands ">  Shows the demands of a net using Metanet or Scigraph  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>ShowDemands()  </CALLING_SEQUENCE_ITEM>
  <CALLING_SEQUENCE_ITEM>ShowDemands(nodes,demands,dmin,dmax)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <P>  </P>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>%net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : the global NetList variable databasis
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nodes  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (nodes)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>demands  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : string or row vector of integers (demands)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>dmin,dmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : reals, minimum and maximum demands   
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
     ShowDemands shows the demands of NetList that their volume is between
    dmin and dmax. All the demands are shown if nothing is indicated)
  </P>
  <P>
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=TrafficExample('Steenbrink');
ShowDemands() // Shows the net
ShowDemands('all','between',100,200)
ShowDemands('used','between',100,200)
// Shows the net with the demands between 100 and 200,
// and the used nodes.
ShowDemands('used',[1 3 8 12],100,200)
// Shows the given demands with values between 100 and 200
   ]]></VERBATIM>
  <P>
    
  </P>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowLinks</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficExample</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>NetList</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/iaon.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>IAON  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="IAON ">  Iterated All or Nothing traffic assignment algorithm  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[f,ta,ben]=IAON(net,k)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>k  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : number of iterations of the algorithm
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>f  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow (disaggregated by commodity)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : row vector of reals, current time for the assigned flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ben  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a kx5 matrix benchmark information.  
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Assigns the flow with the Iterated All or Nothing heuristic.
    Starting with a feasible flow assigned with AON the link costs
    are calculated with the travel time functions. The AON assignment
    is made now with the computed costs and then the costs are recomputed
    for the new assignment. This process is repeated until there is
    no change in the recalculated costs or the number of iterations
    k is reached.
  </P>
  <P>
    The matrix ben contains intermediary informations on the
    algorithm. For each iteration it gives the iteration number, time
    spent, cost, memory used and an convergence error evaluation.
  </P>
  <P>
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample('Small');
[f,ta,ben]=IAON(net,10)
   ]]></VERBATIM>
  <P>
    
  </P>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IA</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/Regular.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>Regular  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="Regular ">  Generation of regular city traffic network data  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>net=Regular(hs,vs,nd)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>hs  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : integer number of horizontal streets
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>vs  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : integer number of vertical streets
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>nd  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : non-negative real parameter related to the OD-pairs (origin-destination)
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : the resulting Netlist 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Generates a NetList consisting in a regular city whose graph is a hsxvs grid
    For the link travel time functions, the data is the same for all links and given
    by t0=ca=ma,ba=1. The lpf_model is 3.
    It is possible to generated 4 different types of Regular City depending on parameter nd:
  </P>
  <P>
    - nd=[] -&gt; The net has all possible O-D pairs all of them with demand equal to 1
  </P>
  <P>
    - nd=1  -&gt; There is only one O-D pair joining the most distant nodes. Demand&apos;s value equal 
    to 1.
  </P>
  <P>
    - nd in (0,1) -&gt; The parameter nd represent the density of O-D pairs present in the net. 
    Demands value equal to 1
  </P>
  <P>
    - nd&gt;1 -&gt; There are [nd] random demands generated. Demands value in the interval [0,15].
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
%net=Regular(4,5);
// generates a network with 4 horizontal streets, 5 vertical streets, 
// (20 nodes, 31 arcs) and all possible OD-pairs:343 
ShowNet();

%net=Regular(4,5,1);
// generates only one demand
ShowNet();

%net=Regular(4,5,0.5);
// generates randomly the OD-pairs with density 0.5
ShowNet();

%net=Regular(4,5,7);
// generates 7 random OD-pairs
ShowNet();

   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>IntroTrfAsg</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficExample</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>ShowNet</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>

=== rishabh110493/scicoslab/contrib/cs5/man/msa.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?> 
<!DOCTYPE MAN SYSTEM "../../man.dtd">
<MAN>
  <LANGUAGE>eng</LANGUAGE>
  <TITLE>MSA  </TITLE>
  <TYPE>Traffic-toolbox Function  </TYPE>
  <DATE>   </DATE>
  <SHORT_DESCRIPTION name="MSA ">  Method of successive averages  </SHORT_DESCRIPTION>
  <CALLING_SEQUENCE>
  <CALLING_SEQUENCE_ITEM>[F,ta,ben]=MSA(net,kmax,tol)  </CALLING_SEQUENCE_ITEM>
  </CALLING_SEQUENCE>
  <P>  </P>
  <PARAM>
 <PARAM_INDENT>
  <PARAM_ITEM>
  <PARAM_NAME>net  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : a NetList
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>kmax  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : maximum number of iterations
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>tol  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : precision
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>F  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : assigned flow
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ta  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : link travel time for the assigned flow f
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
  <PARAM_ITEM>
  <PARAM_NAME>ben  </PARAM_NAME>
  <PARAM_DESCRIPTION>
    : ni x 5 matrix (ni number of performed general iterations) benchmark information 
  </PARAM_DESCRIPTION> 
  </PARAM_ITEM>
 </PARAM_INDENT>
  </PARAM>
  <DESCRIPTION>
  <P>
    Assigns the flow with a MSA heuristic. After an initial AON
    assignment the links costs are updated and a new AON assignment is
    computed. The new flow, f^k+1=(1-lk)*f^k+lk*y^k, where lk=1/k, is computed as a
    combination of the previous flow f^k and an AON assignment y^K.
    This is repeated iteratively until iteration kmax or until the
    precision is reached.
  </P>
  <P>
    The matrix ben contains intermediary informations on the
    algorithm. For each iteration it gives the iteration number, time
    spent, cost, memory used and an convergence error evaluation.
  </P>
  <P>
  </P>
  </DESCRIPTION>
  <ITEMIZE label='EXAMPLES'>
  <VERBATIM><![CDATA[
net=TrafficExample("Steenbrink");
[f,s,ben]=MSA(net,15,1e-3);

   ]]></VERBATIM>
  </ITEMIZE>
  <SEE_ALSO>
    <SEE_ALSO_ITEM> <LINK>AON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>IAON</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>CAPRES</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>FW</LINK> </SEE_ALSO_ITEM>     <SEE_ALSO_ITEM> <LINK>TrafficAssig</LINK> </SEE_ALSO_ITEM>
  </SEE_ALSO>
</MAN>
